# # CREATE USER
# POST http://localhost:3000/users.json
# Content-Type: application/json

# {
#   "name": "Maria Smith",
#   "email": "mariasmith@email.com",
#   "password": "password",
#   "password_confirmation": "password"
# }

# ### CREATE SESSION
# POST http://localhost:3000/sessions.json
# Content-Type: application/json

# {
#   "email": "mariasmith@email.com",
#   "password": "password"
# }

### CREATE TAG
POST http://localhost:3000/tags.json
Content-Type: application/json

{
  "name": "misc",
  "job_id": 1
}